declare const _default: {
    'proximiio:languages': {
        en: {
            title: string;
            level: {
                zero: string;
                one: string;
                two: string;
                few: string;
                many: string;
                other: string;
            };
            meter: {
                zero: string;
                one: string;
                two: string;
                few: string;
                many: string;
                other: string;
            };
            turn_before: string;
            turn_prepare: string;
            turn_now: string;
            continue: string;
            levelchange: string;
            turn_left_hard: string;
            turn_left: string;
            turn_left_slight: string;
            turn_straight: string;
            turn_right_slight: string;
            turn_right: string;
            turn_right_hard: string;
            turn_around: string;
            destination_nearing: string;
            destination_reached: string;
            canceled: string;
            calculating: string;
            recalculating: string;
            path_not_found: string;
            level_change_down: string;
            level_change_up: string;
            passing_poi: string;
            left: string;
            right: string;
        };
        fi: {
            title: string;
            level: {
                zero: string;
                one: string;
                two: string;
                few: string;
                many: string;
                other: string;
            };
            meter: {
                zero: string;
                one: string;
                two: string;
                few: string;
                many: string;
                other: string;
            };
            turn_before: string;
            turn_prepare: string;
            turn_now: string;
            continue: string;
            levelchange: string;
            turn_left_hard: string;
            turn_left: string;
            turn_left_slight: string;
            turn_straight: string;
            turn_right_slight: string;
            turn_right: string;
            turn_right_hard: string;
            turn_around: string;
            destination_nearing: string;
            destination_reached: string;
            canceled: string;
            calculating: string;
            recalculating: string;
            path_not_found: string;
            level_change_down: string;
            level_change_up: string;
            passing_poi: string;
            left: string;
            right: string;
        };
    };
    en: {
        title: string;
        level: {
            zero: string;
            one: string;
            two: string;
            few: string;
            many: string;
            other: string;
        };
        meter: {
            zero: string;
            one: string;
            two: string;
            few: string;
            many: string;
            other: string;
        };
        turn_before: string;
        turn_prepare: string;
        turn_now: string;
        continue: string;
        levelchange: string;
        turn_left_hard: string;
        turn_left: string;
        turn_left_slight: string;
        turn_straight: string;
        turn_right_slight: string;
        turn_right: string;
        turn_right_hard: string;
        turn_around: string;
        destination_nearing: string;
        destination_reached: string;
        canceled: string;
        calculating: string;
        recalculating: string;
        path_not_found: string;
        level_change_down: string;
        level_change_up: string;
        passing_poi: string;
        left: string;
        right: string;
    };
};
export default _default;
