import Feature from '../../models/feature';
import { GuidanceStep } from '../../models/wayfinding';
import { FloorModel } from '../../models/floor';
export default class GuidanceStepsGenerator {
    points: Feature[];
    steps: GuidanceStep[];
    language: string;
    stepsNavigation: 'disabled' | 'simple' | 'simple-levelChangers' | 'full' | 'full-levelChangers' | 'landmark' | 'landmark-levelChangers';
    pois?: Feature[];
    levelChangers?: Feature[];
    initialBearing: number;
    landmarkSteps: boolean;
    fullSteps: boolean;
    simpleSteps: boolean;
    levelChangersSteps: boolean;
    floors: FloorModel[];
    currentFloor: FloorModel;
    constructor({ points, language, stepsNavigation, pois, levelChangers, initialBearing, floors, currentFloor, }: {
        points: Feature[];
        language: string;
        stepsNavigation: 'disabled' | 'simple' | 'simple-levelChangers' | 'full' | 'full-levelChangers' | 'landmark' | 'landmark-levelChangers';
        pois?: Feature[];
        levelChangers?: Feature[];
        initialBearing: number;
        floors: FloorModel[];
        currentFloor: FloorModel;
    });
    private capitalize;
    private generateStepsFromPoints;
    private generateInstruction;
    private generateSimpleInstruction;
    private generateFullInstruction;
    private generateFullLevelChangerInstruction;
    private generateLevelChangerStepInstruction;
    private generateLandmarkInstruction;
    private getLandmarkLevelChangerPrefix;
    private getLandmarkInitialBearingPrefix;
    private getLandmarkDistancePrefix;
    private getLandmarkDirectionWithContext;
    private getDirectionInstruction;
    private getBearingFromLastStep;
    private getStepDirection;
    private getDirectionFromBearing;
    private getDistanceFromLastStep;
    private getLevelChangerDirection;
    private getLineStringFeatureFromLastStep;
    private degreeNormalized;
}
