name: Sync Space
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: idlefingers/do-space-sync-action@master
        with:
          args: --acl public-read
          source_dir: './lib'
        env:
          SPACE_NAME: 'proximiiojs'
          SPACE_REGION: 'ams3'
          SPACE_ACCESS_KEY: ${{ secrets.SPACE_ACCESS_KEY }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
