name: Deploy to DigitalOcean CDN
on: push
#  push:
#    tags:
#      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Configure AWS CLI for DigitalOcean Spaces
        run: |
          aws configure set aws_access_key_id ${{ secrets.SPACE_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}

      - name: Upload to versioned folder
        run: |
          aws --endpoint-url=https://ams3.digitaloceanspaces.com \
            s3 sync ./lib s3://proximiiojs/v${TAG_NAME}/ --acl public-read

      - name: Also update /latest (optional)
        run: |
          aws --endpoint-url=https://ams3.digitaloceanspaces.com \
            s3 sync ./lib s3://proximiiojs/latest/ --acl public-read
