name: Sync Space
on: push
#  push:
#    tags:
#      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check lib folder exists
        run: |
          if [ ! -d "./lib" ]; then
            echo "lib folder does not exist!"
            exit 1
          fi

      - name: Sync to DigitalOcean Space
        uses: idlefingers/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: './lib'
          SPACE_NAME: 'proximiiojs'
          SPACE_REGION: 'ams3'
          SPACE_ACCESS_KEY: ${{ secrets.SPACE_ACCESS_KEY }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
